# Generated by Django 2.1.2 on 2018-11-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='external_id',
        ),
    ]
