# Generated by Django 2.1.2 on 2018-11-18 08:52

import api.models.profile
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181116_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Код')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Phone', verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.IntegerField(default=api.models.profile.Profile.get_new_external_id, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
