# Generated by Django 2.1.2 on 2018-11-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181118_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Phone', verbose_name='Номер телефона'),
        ),
    ]
