# Generated by Django 2.1.2 on 2018-11-20 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181119_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True, verbose_name='Токен')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Phone', verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Токен аутентификации',
                'verbose_name_plural': 'Токены аутентификации',
            },
        ),
    ]
