# Generated by Django 2.1.2 on 2018-11-21 05:00

import api.models.sms_code
import api.models.token
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(default=api.models.sms_code.SmsCode.get_new_code, max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, default=api.models.token.Token.get_new_token, max_length=100, unique=True, verbose_name='Токен'),
        ),
    ]
