# Generated by Django 2.1 on 2018-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181121_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
    ]
