# Generated by Django 2.1.2 on 2018-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181129_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Тестовый баланс'),
        ),
    ]
