# Generated by Django 2.1.2 on 2018-12-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_test_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Сумма перевода')),
                ('type', models.CharField(choices=[('tip_payment', 'Оплата чаевых'), ('withdraw', 'Снятие со счета')], default='tip_payment', max_length=11, verbose_name='Тип транзакции')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile', verbose_name='Кому перевод')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
