# Generated by Django 2.1.2 on 2018-12-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='test_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Тестовый баланс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма перевода'),
        ),
    ]
