# Generated by Django 2.1.2 on 2019-02-12 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_transaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата запроса')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('paid', 'Выплачено'), ('declined', 'Отказано')], default='pending', max_length=8, verbose_name='Статус')),
                ('reviewed_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время рассмотрения')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Запрос на вывод средств',
                'verbose_name_plural': 'Запросы на вывод средств',
            },
        ),
    ]
