# Generated by Django 2.1.2 on 2019-02-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_withdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile', verbose_name='Профиль'),
        ),
    ]
