# Generated by Django 2.1.2 on 2019-02-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0004_auto_20181128_1642'),
        ('api', '0021_auto_20190213_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='are_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Уведомления включены?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fcm_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fcm_django.FCMDevice', verbose_name='Устройства'),
        ),
    ]
