# Generated by Django 2.1.2 on 2019-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0004_auto_20181128_1642'),
        ('api', '0022_auto_20190214_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fcm_devices',
        ),
        migrations.AddField(
            model_name='profile',
            name='fcm_devices',
            field=models.ManyToManyField(blank=True, to='fcm_django.FCMDevice', verbose_name='Устройства'),
        ),
    ]
