# Generated by Django 2.1.2 on 2019-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190216_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='reviewed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время рассмотрения'),
        ),
    ]
