# Generated by Django 2.1.2 on 2019-03-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_user',
            new_name='recipient',
        ),
    ]
