# Generated by Django 2.2.3 on 2019-07-21 13:32

import api.models.profile
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190316_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscode',
            options={'verbose_name': 'Код подтверждения', 'verbose_name_plural': 'Коды подтверждения'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.IntegerField(default=api.models.profile.Profile.get_new_external_id, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')], verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.Phone', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='api.Phone', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='token',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='token', to='api.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Profile', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='api.Profile', verbose_name='Профиль'),
        ),
    ]
