# Generated by Django 2.2.3 on 2019-08-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190721_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='api.Profile', verbose_name='Профиль'),
        ),
    ]
